### ISSUE TITLE
[Mod Suggestion] Better Compatibility Checker

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica9#222]
### URL

https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker

### Why would you like the mod added?

I would say pretty useful QoL mod, that will definitely help with confusion on what version server is. Need to test how it functions if client version (aka: Any version below the update that adds this mod 😅) doesn't have it, but I'm fairly sure it will help in the future 😄

Was planning on suggesting it for Enigmatica 8 as well, but I don't think there will be a lot of updates to E8 at this point, so not sure if it would be useful at all there.

**Comment by Kanzaji** [comment]
Found one thing that would needed to be changed already https://github.com/Aizistral-Studios/No-Chat-Reports/issues/343#issuecomment-1370325111 , but that isn't a huge issue 😄

`\config\NoChatReports\NCR-Client.json`
```
  "verifiedIconOffsetX": -14,
  "verifiedIconOffsetY": 0,
```

bcc-common.toml
```toml
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 632239
	#The name of the modpack
	modpackName = "Enigmatica 9"
	#The version of the modpack
	modpackVersion = "DEVELOP"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
```
Metadata function was created specifically for FTB, but we could technically use it as well.
